project:
  type: book
  output-dir: docs
  pre-render: load_and_transform_data.R

book:
  title: "MRP Parameter Optimization with BO"
  author: 
    - "Philipp Zmijewksi"
    - "Nicolas Meseth"
    
  date: 2023-05-09
  
  chapters:
    - index.qmd
    - data.qmd
    - transformations.qmd
    - exploration.qmd
    - results_summary.qmd
    - convergence.qmd
    - reliability.qmd
    - sobol.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: paged
    code-fold: true
    toc: true

execute: 
  warning: false



