project:
  type: book
  output-dir: web

book:
  title: "MRP Parameter Optimization with BO"
  author: 
    - "Philipp Zmijewksi"
    - "Nicolas Meseth"
    
  date: 2023-04-17
  
  chapters:
    - index.qmd
    - data.qmd
    - transformations.qmd
    - exploration.qmd
    - summary_plots.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    df-print: paged
    code-fold: true
    toc: true

execute: 
  warning: false



